Repository MLH-Fellowship/alphadoc, pull requests merged in 2021-01, with the labels that each got.

#19 Integrate Welcome and Greeting Bot
  .github/config.yml
Labels: DWOC, Level-4

#21 Add Contributors Table in README.md
  README.md
Labels: DWOC, Level-1

#22 Add Templates for Pull Request
  .github/pull_request_template.md
Labels: DWOC, Level-1, documentation

#25 add contributors image (#23)
  README.md
Labels: DWOC, Level-1, documentation
